version: '3'

#
# Have a look at the .env file -> used for configuration
#

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "0.0.0.0:15672:15672"
      - "0.0.0.0:5672:5672"
    hostname: ataka-rabbitmq
    networks:
      - ataka
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  postgres:
    image: postgres:14-alpine
    hostname: ataka-postgres
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - ataka
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer:latest
    ports:
      - "0.0.0.0:8080:8080"
    hostname: ataka-adminer
    networks:
      - ataka
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  web:
    image: cyberwehr/ataka-web
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/web/Dockerfile
    volumes:
      - ${DATA_STORE}/shared:/data/shared:rw,z
      - ${DATA_STORE}/exploits:/data/exploits:rw,z
      - ./ataka/web:/ataka/web
    ports:
      - "0.0.0.0:8000:8000"
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-web
    networks:
      - ataka
    env_file:
      - .env

  ui:
    image: cyberwehr/ataka-ui
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/ui/Dockerfile
    volumes:
      - ./ataka/ui:/ataka/ui
    ports:
      - "0.0.0.0:80:8080"
    security_opt:
      - label:disable
    depends_on:
      - web
    hostname: ataka-ui
    networks:
      - ataka
    env_file:
      - .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  executor:
    image: cyberwehr/ataka-executor
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/executor/Dockerfile
    volumes:
      - /var/run/docker.sock:/run/docker.sock:rw
      - ${DATA_STORE}/shared:/data/shared:rw,z
      - ${DATA_STORE}/exploits:/data/exploits:rw,z
      - ${DATA_STORE}/persist:/data/persist:rw,z
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-executor
    networks:
      - ataka
    env_file:
      - .env

  ctfcode:
    image: cyberwehr/ataka-ctfcode
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/ctfcode/Dockerfile
    volumes:
      - ./ataka/ctfconfig:/ataka/ctfconfig:ro
      - ${DATA_STORE}/shared:/data/shared:rw,z
    security_opt:
      - label:disable
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-ctfcode
    networks:
      - ataka
    env_file:
      - .env

  cli:
    image: cyberwehr/ataka-cli
    user: $USERID
    build:
      context: ./
      dockerfile: ataka/cli/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    hostname: ataka-cli
    networks:
      - ataka
    env_file:
      - .env

networks:
  ataka:
